/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
import javax.swing.JOptionPane;
/**
 *
 * @author ATHOSFELIPENASCIMENT
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNumero1 = new javax.swing.JTextField();
        campoNumero2 = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        somar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        subtrair = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoNumero1.setText("Digite um número...");
        campoNumero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNumero1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumero1FocusLost(evt);
            }
        });
        campoNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero1ActionPerformed(evt);
            }
        });

        campoNumero2.setText("Digite outro número...");
        campoNumero2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNumero2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumero2FocusLost(evt);
            }
        });
        campoNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero2ActionPerformed(evt);
            }
        });

        titulo.setText("Calculadora");

        somar.setText("+");
        somar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somarActionPerformed(evt);
            }
        });

        dividir.setText("/");
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });

        subtrair.setText("-");
        subtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtrairActionPerformed(evt);
            }
        });

        multiplicar.setText("*");
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });

        resultado.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multiplicar)
                                    .addComponent(somar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtrair)
                                    .addComponent(dividir)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(resultado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNumero1)
                            .addComponent(campoNumero2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(somar)
                    .addComponent(subtrair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicar)
                    .addComponent(dividir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultado)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero1ActionPerformed

    private void campoNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero2ActionPerformed

    private void somarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somarActionPerformed
          //System.out.println("Botão clicado! ");
        // Para pegar o texto de algum campo, usamos o método nomeDoComponente.getText();
        String numero1 = campoNumero1.getText();
        String numero2 = campoNumero2.getText();
        
        // O método Integer.parseint() converte um número em String para Int
        int numero1Int = Integer.parseInt(numero1);
        int numero2Int = Integer.parseInt(numero2);
        
        int soma = numero1Int + numero2Int;
        // Para trocar o texto de algum componente, usamos o método nomeDoComponente.setText("novo texto")
        resultado.setText("Resultado: " + soma);
    
    }//GEN-LAST:event_somarActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        String numero1 = campoNumero1.getText();
        String numero2 = campoNumero2.getText();
        int numero1Int = Integer.parseInt(numero1);
        int numero2Int = Integer.parseInt(numero2);
        if(numero2Int == 0){
        JOptionPane.showMessageDialog(this,"Impossível dividir por zero");
        } else{
        int divisao = numero1Int / numero2Int;
        resultado.setText("Resultado: " + divisao);
    }//GEN-LAST:event_dividirActionPerformed
    }
    private void subtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtrairActionPerformed
        // TODO add your handling code here:
         String numero1 = campoNumero1.getText();
        String numero2 = campoNumero2.getText();
        int numero1Int = Integer.parseInt(numero1);
        int numero2Int = Integer.parseInt(numero2);
        int subtrair = numero1Int - numero2Int;
        resultado.setText("Resultado: " + subtrair);
    }//GEN-LAST:event_subtrairActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        // TODO add your handling code here:
         String numero1 = campoNumero1.getText();
        String numero2 = campoNumero2.getText();
        int numero1Int = Integer.parseInt(numero1);
        int numero2Int = Integer.parseInt(numero2);
        int multiplicar = numero1Int * numero2Int;
        resultado.setText("Resultado: " + multiplicar);
    }//GEN-LAST:event_multiplicarActionPerformed

    private void campoNumero1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumero1FocusGained
        // TODO add your handling code here:
         // Se o texto do campo for igual a 'Digite um número...'
        // ele apaga o textp
        // para isso, primeiro, eu preciso pegar o texto escrito no cmapo
        // e aí, comparar se é igual a 'Digite um número'
        // o método .equals() compara se uma String é igual a outra
        if ("Digite um número...".equals(campoNumero1.getText())){
        campoNumero1.setText("");

    }//GEN-LAST:event_campoNumero1FocusGained
    }
    private void campoNumero2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumero2FocusGained
        if ("Digite outro número...".equals(campoNumero2.getText())){
        campoNumero2.setText("");
        }
    }//GEN-LAST:event_campoNumero2FocusGained

    private void campoNumero1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumero1FocusLost
        // TODO add your handling code here:
          // Se eu não digitei nada
        // ele volta ao texto original
        if ("".equals(campoNumero1.getText())) {
            campoNumero1.setText("Digite um número...");
        }
    }//GEN-LAST:event_campoNumero1FocusLost

    private void campoNumero2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumero2FocusLost
        // TODO add your handling code here:
           if ("".equals(campoNumero2.getText())) {
            campoNumero2.setText("Digite outro número...");
        }
    }//GEN-LAST:event_campoNumero2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNumero1;
    private javax.swing.JTextField campoNumero2;
    private javax.swing.JButton dividir;
    private javax.swing.JButton multiplicar;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton somar;
    private javax.swing.JButton subtrair;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
