/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package revisao01;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
       int[] numeros;
       
       numeros = new int[5];
       numeros[0] = 50;
       numeros[1] = 60;
       numeros[2] = 70;
       numeros[3] = 80;
       numeros[4] = 90;
  
       
       for(int i = 0; i < numeros.length; i ++){
           System.out.println(numeros[i]);   
       }
       
       String[] nomes = {"athos", "decks","isoca"};
       for(int i = 0; i < nomes.length; i ++){
           System.out.println(nomes[i]);   
       }
       
       Arrays.sort(numeros);
        System.out.println("Arrays ordenados");
        for(int i = 0; i < numeros.length; i ++) {
            System.out.println(numeros[i]);   
        }
       
       
       String texto = Arrays.toString(numeros);
        System.out.println(texto);
       
        int index = Arrays.binarySearch(numeros, 87);
        System.out.println(index);
        
        int [] a = {1, 2, 3};
        int [] b = {1,2,3};
        System.out.println(Arrays.equals(a, b));
    }
}
