/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package usandoScanner;
import java.util.Scanner;
import javax.sound.midi.SoundbankResource;

public class App {
   
    public static void main(String[] args) {
        // Crua um objeto Scanner para ler a entrada do usuário
        Scanner sc = new Scanner(System.in);
        
        int num1, num2;
        System.out.println("Digite um numero: ");
        // Armazenar um número inteiro passado pelo usuário
        num1 = sc.nextInt();
        System.out.println(num1);
        
        System.out.println("Digite o segundo numero: ");
        num2 = sc.nextInt();
        
        System.out.println("Soma: " + (num1 + num2));
        sc.nextLine();
        System.out.println("Digite seu nome: ");
        String nome = sc.nextLine(); // para strings
        
        System.out.println("Digite sua altura: ");
        double altura = sc.nextDouble(); // para doubles
        
        System.out.println("Olá "+ nome +", voce tem "+ altura +" de altura" );
    }
}
