/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tratamentoDeExcessoes;

import java.io.FileReader;
import java.io.IOException;

public class App {
    
    static int[] numeros = {10,5,90 }; // 0, 1, 2

    public static void main(String[] args) {
        double resultado = Divisao.dividir(10,0);
           System.out.println(resultado);
           
           // dentro do try, colocamos o código que queremos executar
           // mas que pode gerar um erro (excessão)
           try {
               System.out.println(numeros[2]);
           } 
           // catch captura o erro e podemos mostrar a mensagem de forma clara
           catch (Exception erro) {
               System.out.println("Erro: " + erro.getMessage());
           }
           
           try{
                FileReader arquivo = new FileReader("arquivo.txt");
           } catch(IOException e){
               System.out.println("Erro ao tentar abrir o arquivo: " + e.getMessage());
           }
    }
}
