/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoRPG;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        int rolarDados = Personagem.rolarDados(1, 6);
        System.out.println(rolarDados);
              
    }
}
