/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoRPG;

import javax.swing.JOptionPane;

/**
 *
 * @author HEITORSCHAFERLIMA
 */
public class Batalha extends javax.swing.JFrame {

    /**
     * Creates new form Batalha
     */
 
    private int agilidade;
    
    private Personagem jogador;
    private Inimigo inimigo;
    
   
    
    public Batalha(Personagem jogador) {
        initComponents();
        this.jogador = jogador;
        atualizarInterface();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelPersonagem = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelVida = new javax.swing.JLabel();
        labelMana = new javax.swing.JLabel();
        barraVida = new javax.swing.JProgressBar();
        barraMana = new javax.swing.JProgressBar();
        btnAtacar = new javax.swing.JButton();
        btnHabilidade = new javax.swing.JButton();
        btnItem = new javax.swing.JButton();
        btnFugir = new javax.swing.JButton();
        comboInventario = new javax.swing.JComboBox<>();
        labelNomeInimigo = new javax.swing.JLabel();
        labelVidaInimigo = new javax.swing.JLabel();
        labelManaInimigo = new javax.swing.JLabel();
        barraManaInimigo = new javax.swing.JProgressBar();
        barraVidaInimigo = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaNarrador = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        labelInimigo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        labelPersonagem.setBackground(new java.awt.Color(255, 255, 255));
        labelPersonagem.setForeground(new java.awt.Color(0, 0, 0));
        labelPersonagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blank2.png"))); // NOI18N

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(0, 0, 0));
        labelNome.setText("Hector");

        labelVida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVida.setForeground(new java.awt.Color(0, 0, 0));
        labelVida.setText("Vida: 50/100");

        labelMana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMana.setForeground(new java.awt.Color(0, 0, 0));
        labelMana.setText("Mana: 30/60");

        barraVida.setBackground(new java.awt.Color(102, 0, 0));
        barraVida.setForeground(new java.awt.Color(255, 0, 0));
        barraVida.setValue(50);

        barraMana.setBackground(new java.awt.Color(0, 102, 0));
        barraMana.setForeground(new java.awt.Color(0, 255, 0));
        barraMana.setValue(50);

        btnAtacar.setBackground(new java.awt.Color(204, 204, 204));
        btnAtacar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnAtacar.setForeground(new java.awt.Color(0, 0, 0));
        btnAtacar.setText("Atacar");
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });

        btnHabilidade.setBackground(new java.awt.Color(204, 204, 204));
        btnHabilidade.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnHabilidade.setForeground(new java.awt.Color(0, 0, 0));
        btnHabilidade.setText("Habilidade");
        btnHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilidadeActionPerformed(evt);
            }
        });

        btnItem.setBackground(new java.awt.Color(204, 204, 204));
        btnItem.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnItem.setForeground(new java.awt.Color(0, 0, 0));
        btnItem.setText("Item");
        btnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemActionPerformed(evt);
            }
        });

        btnFugir.setBackground(new java.awt.Color(204, 204, 204));
        btnFugir.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnFugir.setForeground(new java.awt.Color(0, 0, 0));
        btnFugir.setText("Fugir");
        btnFugir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFugirActionPerformed(evt);
            }
        });

        comboInventario.setBackground(new java.awt.Color(255, 255, 255));
        comboInventario.setForeground(new java.awt.Color(0, 0, 0));
        comboInventario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poção de Força", "Poção de Cura", "Poção de Dano" }));

        labelNomeInimigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNomeInimigo.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeInimigo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelNomeInimigo.setText("Eis que leto");

        labelVidaInimigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVidaInimigo.setForeground(new java.awt.Color(0, 0, 0));
        labelVidaInimigo.setText("Vida: 50/100");

        labelManaInimigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelManaInimigo.setForeground(new java.awt.Color(0, 0, 0));
        labelManaInimigo.setText("Mana: 30/60");

        barraManaInimigo.setBackground(new java.awt.Color(0, 102, 0));
        barraManaInimigo.setForeground(new java.awt.Color(0, 255, 0));
        barraManaInimigo.setValue(50);

        barraVidaInimigo.setBackground(new java.awt.Color(102, 0, 0));
        barraVidaInimigo.setForeground(new java.awt.Color(255, 0, 0));
        barraVidaInimigo.setValue(50);

        areaNarrador.setEditable(false);
        areaNarrador.setBackground(new java.awt.Color(255, 255, 255));
        areaNarrador.setColumns(18);
        areaNarrador.setForeground(new java.awt.Color(0, 0, 0));
        areaNarrador.setLineWrap(true);
        areaNarrador.setRows(4);
        areaNarrador.setText("Hector atacou Eis que leto!\nEis que leto atacou Hector!\nHector usou Poção de Força e ganhou 3 pontos de força!\nEis que leto atacou Hector!");
        areaNarrador.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaNarrador);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inventário");

        labelInimigo.setBackground(new java.awt.Color(255, 255, 255));
        labelInimigo.setForeground(new java.awt.Color(0, 0, 0));
        labelInimigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInimigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blank2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPersonagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNomeInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAtacar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(btnItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnFugir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHabilidade, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelVida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelMana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barraVida, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barraMana, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(comboInventario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelVidaInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelManaInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barraVidaInimigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barraManaInimigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelNomeInimigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(labelVida)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelMana))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(barraVidaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(barraManaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelVidaInimigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelManaInimigo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(barraVida, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraMana, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtacar)
                            .addComponent(btnHabilidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnItem)
                            .addComponent(btnFugir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        // TODO add your handling code here:
          // Jogador ataca
        String logJogador = jogador.atacar(inimigo);
        areaNarrador.append(logJogador + "\n");

        // Se o inimigo ainda estiver vivo, ele contra-ataca
        if (inimigo.estaVivo()) {
            String logInimigo = inimigo.atacar(jogador);
            areaNarrador.append(logInimigo + "\n");
        }

        atualizarInterface();
        checarFimDoCombate();
        
    }//GEN-LAST:event_btnAtacarActionPerformed

    private void btnHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidadeActionPerformed
        // TODO add your handling code here:
          // Jogador usa habilidade
        String logJogador = jogador.usarHabilidade(inimigo);
        areaNarrador.append(logJogador + "\n");

        // Contra-ataque do inimigo se ele não tiver morrido
        if (inimigo.estaVivo()) {
            String logInimigo = inimigo.atacar(jogador);
            areaNarrador.append(logInimigo + "\n");
        }

        atualizarInterface();
        checarFimDoCombate();
    }//GEN-LAST:event_btnHabilidadeActionPerformed

    private void btnFugirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFugirActionPerformed
        // TODO add your handling code here:
        // Jogador tenta fugir
        String log = jogador.fugir(inimigo);
        areaNarrador.append(log + "\n");

        // Se falhar, inimigo ataca
        if (log.contains("falhou")) {
            String logInimigo = inimigo.atacar(jogador);
            areaNarrador.append(logInimigo + "\n");

            atualizarInterface();
            checarFimDoCombate();
        } else {
            JOptionPane.showMessageDialog(this, "Você escapou!");
            this.dispose(); // fecha a tela de batalha
        }
    }//GEN-LAST:event_btnFugirActionPerformed

    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed
        // TODO add your handling code here:
        Item item = ItemFactory.gerarItemAleatorio();

        String log = jogador.usarItem(item);

        areaNarrador.append(log + "\n");

        atualizarInterface();
    }//GEN-LAST:event_btnItemActionPerformed
    
    private void atualizarInterface() {
        // JOGADOR  
        labelNome.setText(jogador.getNome());
        labelVida.setText("Vida: " + jogador.getVida());
        barraVida.setValue(jogador.getVida());

        // INIMIGO
        labelNomeInimigo.setText(inimigo.getNome());
        labelVidaInimigo.setText("Vida: " + inimigo.getVida());
        barraVidaInimigo.setValue(inimigo.getVida());
    }
    
    private void checarFimDoCombate() {
        if (!jogador.estaVivo()) {
            JOptionPane.showMessageDialog(this, "Você foi derrotado!");
            this.dispose();
        } 
        else if (!inimigo.estaVivo()) {
            JOptionPane.showMessageDialog(this, "Você derrotou o inimigo!");
            this.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaNarrador;
    private javax.swing.JProgressBar barraMana;
    private javax.swing.JProgressBar barraManaInimigo;
    private javax.swing.JProgressBar barraVida;
    private javax.swing.JProgressBar barraVidaInimigo;
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnFugir;
    private javax.swing.JButton btnHabilidade;
    private javax.swing.JButton btnItem;
    private javax.swing.JComboBox<String> comboInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInimigo;
    private javax.swing.JLabel labelMana;
    private javax.swing.JLabel labelManaInimigo;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeInimigo;
    private javax.swing.JLabel labelPersonagem;
    private javax.swing.JLabel labelVida;
    private javax.swing.JLabel labelVidaInimigo;
    // End of variables declaration//GEN-END:variables
}
