/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ProjetoRPG;


/**
 *
 * @author HEITORSCHAFERLIMA
 */
public class TelaJogo extends javax.swing.JFrame {

    private String nomePersonagem;
    private int vidaPersonagem;
    private int forcaPersonagem;
    private int agilidadePersonagem;
    private int manaPersonagem;
    
    public TelaJogo() {
        initComponents();
        setLocationRelativeTo(null); // Centraliza o JFrame na tela

    }
    
    public TelaJogo(String nome, int vida, int forca, int agilidade, int mana) {
        initComponents();
        this.nomePersonagem = nome;
        labelNome.setText("Nome: "  + nome);
        this.vidaPersonagem = vida;
        labelVida.setText("Vida: " + vida);
        this.forcaPersonagem = forca;
        labelForca.setText("Força: " + String.valueOf(forca));
        this.agilidadePersonagem = agilidade;
        labelAgilidade.setText("Agilidade: " + String.valueOf(agilidade));
        this.manaPersonagem = mana;
        labelMana.setText("Mana: " + String.valueOf(mana));
        barraVida.setValue(vida);
        barraMana.setValue(mana);
         
        
    } 
    /**
     * Creates new form Jogo
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTela = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelVida = new javax.swing.JLabel();
        labelMana = new javax.swing.JLabel();
        labelForca = new javax.swing.JLabel();
        labelAgilidade = new javax.swing.JLabel();
        barraVida = new javax.swing.JProgressBar();
        barraMana = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaNarrador = new javax.swing.JTextArea();
        btnOpcao1 = new javax.swing.JButton();
        btnOpcao2 = new javax.swing.JButton();
        btnRolarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        labelTela.setBackground(new java.awt.Color(255, 255, 255));
        labelTela.setForeground(new java.awt.Color(0, 0, 0));
        labelTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blank.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Seu personagem:");

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(0, 0, 0));
        labelNome.setText("Nome: ");

        labelVida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVida.setForeground(new java.awt.Color(0, 0, 0));
        labelVida.setText("Vida:");

        labelMana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMana.setForeground(new java.awt.Color(0, 0, 0));
        labelMana.setText("Mana: ");

        labelForca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelForca.setForeground(new java.awt.Color(0, 0, 0));
        labelForca.setText("Força:");

        labelAgilidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAgilidade.setForeground(new java.awt.Color(0, 0, 0));
        labelAgilidade.setText("Agilidade:");

        barraVida.setBackground(new java.awt.Color(0, 102, 0));
        barraVida.setForeground(new java.awt.Color(51, 255, 0));
        barraVida.setValue(50);

        barraMana.setBackground(new java.awt.Color(0, 0, 102));
        barraMana.setForeground(new java.awt.Color(51, 51, 255));
        barraMana.setValue(50);

        areaNarrador.setEditable(false);
        areaNarrador.setBackground(new java.awt.Color(255, 255, 255));
        areaNarrador.setColumns(18);
        areaNarrador.setForeground(new java.awt.Color(0, 0, 0));
        areaNarrador.setLineWrap(true);
        areaNarrador.setRows(5);
        areaNarrador.setText("Ao sair da cidade, você vê que o caminho se divide em dois. Por onde você vai?");
        areaNarrador.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaNarrador);

        btnOpcao1.setBackground(new java.awt.Color(204, 204, 204));
        btnOpcao1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnOpcao1.setForeground(new java.awt.Color(0, 0, 0));
        btnOpcao1.setText("Esquerda");

        btnOpcao2.setBackground(new java.awt.Color(204, 204, 204));
        btnOpcao2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnOpcao2.setForeground(new java.awt.Color(0, 0, 0));
        btnOpcao2.setText("Direita");

        btnRolarDados.setBackground(new java.awt.Color(204, 204, 204));
        btnRolarDados.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnRolarDados.setForeground(new java.awt.Color(0, 0, 0));
        btnRolarDados.setText("Rolar Dados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTela, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelAgilidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(labelForca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelVida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barraVida, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraMana, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRolarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barraMana, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelTela, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelVida)
                                    .addComponent(barraVida, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMana))
                            .addComponent(jScrollPane1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOpcao1)
                        .addComponent(btnOpcao2))
                    .addComponent(labelForca, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgilidade)
                    .addComponent(btnRolarDados))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaNarrador;
    private javax.swing.JProgressBar barraMana;
    private javax.swing.JProgressBar barraVida;
    private javax.swing.JButton btnOpcao1;
    private javax.swing.JButton btnOpcao2;
    private javax.swing.JButton btnRolarDados;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAgilidade;
    private javax.swing.JLabel labelForca;
    private javax.swing.JLabel labelMana;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTela;
    private javax.swing.JLabel labelVida;
    // End of variables declaration//GEN-END:variables
}
