/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoRPG;

/**
 *
 * @author HEITORSCHAFERLIMA
 */
public class TelaInicial extends javax.swing.JFrame {
    
    
    
    private int vidaGerada;
    private int manaGerada;
    private int forcaGerada;
    private int agilidadeGerada;
    
     private Personagem personagem; // vamos usar depois
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
         setLocationRelativeTo(null); // Centraliza o JFrame na tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        btnComecar = new javax.swing.JButton();
        comboClasses = new javax.swing.JComboBox<>();
        botaoGerarMana = new javax.swing.JButton();
        botaoGerarForça = new javax.swing.JButton();
        botaoGerarVida = new javax.swing.JButton();
        botaoGerarAgilidade = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reino Royale the Game");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bem vindo! Escolha um nome e classe para seu personagem:");

        fieldNome.setBackground(new java.awt.Color(255, 255, 255));
        fieldNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldNome.setForeground(new java.awt.Color(0, 0, 0));
        fieldNome.setText("Digite um nome...");

        btnComecar.setBackground(new java.awt.Color(0, 204, 0));
        btnComecar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComecar.setForeground(new java.awt.Color(0, 0, 0));
        btnComecar.setText("Começar");
        btnComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecarActionPerformed(evt);
            }
        });

        comboClasses.setBackground(new java.awt.Color(255, 255, 255));
        comboClasses.setForeground(new java.awt.Color(0, 0, 0));
        comboClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cavaleiro", "Mago ", "Ladino", "Arqueiro Celestial" }));
        comboClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClassesActionPerformed(evt);
            }
        });

        botaoGerarMana.setText("Role dados para gerar mana!");
        botaoGerarMana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarManaActionPerformed(evt);
            }
        });

        botaoGerarForça.setText("Role dados para gerar força!");
        botaoGerarForça.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarForçaActionPerformed(evt);
            }
        });

        botaoGerarVida.setText("Role dados para gerar vida!");
        botaoGerarVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarVidaActionPerformed(evt);
            }
        });

        botaoGerarAgilidade.setText("Role dados para gerar agilidade!");
        botaoGerarAgilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarAgilidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoGerarVida)
                                    .addComponent(botaoGerarForça))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoGerarAgilidade)
                                    .addComponent(botaoGerarMana)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(btnComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGerarVida)
                    .addComponent(botaoGerarMana))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGerarForça)
                    .addComponent(botaoGerarAgilidade))
                .addGap(18, 18, 18)
                .addComponent(btnComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Classes disponíveis:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecarActionPerformed
        String nome = fieldNome.getText();
        String classe = comboClasses.getSelectedItem().toString();
        
        
        switch(classe){
            case "Cavaleiro":
                Barbaro personagem = new Barbaro(nome,this.vidaGerada, this.manaGerada, this.forcaGerada + 2, this.agilidadeGerada );
                break;
                
            case "Arqueiro": 
                Arqueiro arqueiro = new Arqueiro(nome, this.vidaGerada, this.manaGerada, this.forcaGerada, this.agilidadeGerada + 3);
                break;
            
            case "Ladino":
                Ladino ladino = new Ladino(nome, this.vidaGerada, this.manaGerada, this.forcaGerada, this.agilidadeGerada + 4);
                break;
            
            case "Mago":
                Mago mago = new Mago(nome, this.vidaGerada, this.manaGerada + 3, this.forcaGerada, this.agilidadeGerada);
                break;
        }
                
                
                
        new TelaJogo(nome, this.vidaGerada, this.forcaGerada, this.agilidadeGerada, this.manaGerada).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnComecarActionPerformed

    private void comboClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClassesActionPerformed

    private void botaoGerarVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarVidaActionPerformed
        // TODO add your handling code here:
        this.vidaGerada = Dados.rolar(4, 20);
        botaoGerarVida.setText("Vida: " + vidaGerada);
        
        
    }//GEN-LAST:event_botaoGerarVidaActionPerformed

    private void botaoGerarManaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarManaActionPerformed
        // TODO add your handling code here:
        this.manaGerada = Dados.rolar(2, 20);
        botaoGerarMana.setText("Mana: " + manaGerada);
        
    }//GEN-LAST:event_botaoGerarManaActionPerformed

    private void botaoGerarForçaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarForçaActionPerformed
        // TODO add your handling code here:
        this.forcaGerada = Dados.rolar(3, 20);
        botaoGerarForça.setText("Força: " + forcaGerada);
        
    }//GEN-LAST:event_botaoGerarForçaActionPerformed

    private void botaoGerarAgilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarAgilidadeActionPerformed
        // TODO add your handling code here:
        this.agilidadeGerada = Dados.rolar(2, 20);
        botaoGerarAgilidade.setText("Agilidade: " + agilidadeGerada);
        
    }//GEN-LAST:event_botaoGerarAgilidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGerarAgilidade;
    private javax.swing.JButton botaoGerarForça;
    private javax.swing.JButton botaoGerarMana;
    private javax.swing.JButton botaoGerarVida;
    private javax.swing.JButton btnComecar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboClasses;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
