 /*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrays;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
         int[] numeros;
       
       numeros = new int[5];
       numeros[0] = 50;
       numeros[1] = 60;
       numeros[2] = 70;
       numeros[3] = 83;
       numeros[4] = 90;
       System.out.println(numeros);
  
       
       for(int i = 0; i < numeros.length; i ++){
           System.out.println(numeros[i]);   
       }
       
       String[] nomes = {"athos", "decks","isoca"};
       for(int i = 0; i < nomes.length; i ++){
           System.out.println(nomes[i]);   
       }
       
       //Arrays.sort ordena todos os numeros do array
       Arrays.sort(numeros);
        System.out.println("Arrays ordenados");
        for(int i = 0; i < numeros.length; i ++) {
            System.out.println(numeros[i]);   
        }
       
       //Array.toString transforma os itens do array para string
       String texto = Arrays.toString(numeros);
        System.out.println(texto);
       
        //Procura dentro de um array ordenado, qual o indice do valor que eu passei
        int index = Arrays.binarySearch(numeros, 80);
        System.out.println(index);
        
        
        //Array equal(array1, array2) compara se dois arrays são iguais
        //retorna true ou false
        int [] a = {1, 2, 5};
        int [] b = {1,2,3};
        System.out.println(Arrays.equals(a, b));
        
        //Arrays.fill transforma todos os itens para um mesmo valor
        int[] notas = {70, 80, 90};
        Arrays.fill(notas, 100);
        System.out.println(Arrays.toString(notas));
        
        //Arrays.copyOf (array, tamanho) cria uma cópia do array original com o tamanho (length) especificado
        int[] copiaNotas = Arrays.copyOf(notas, 5);
        int [] outraCopiaNotas = Arrays.copyOf(notas, 2);
        System.out.println("Array menor: " + Arrays.toString(outraCopiaNotas));
        System.out.println("Array maior: " + Arrays.toString(copiaNotas));
        
        //Arrays.copyOfRange(arrayOriginal, indiceInicial, indiceFinal)
        //Cria uma cópia do array original começando pelo indice inicial e terminando no indice que passamos no fim
        String[] paises = {"Brasil","Russia", "India", "China", "Africa do Sul"};
        String[] paisesAsiaticos = Arrays.copyOfRange(paises, 2, 4);
        System.out.println("Paises asiaticos: " + Arrays.toString(paisesAsiaticos));
        
        
        //Arrays.stream(array) transforma meu array em uma Stream
        //O que basicamente me permite acessar outros métodos
        int[] meusNumeros = {1, 2, 3, 4, 5};
        //.sum() é um deles. Ele soma todos os itens do array.
        System.out.println(Arrays.stream(meusNumeros).sum());
        //. average() calcula a média dos valores do array
        System.out.println(Arrays.stream(meusNumeros).average());
        
        //.filter(condicao) filtra o array/stream de acordo com a condição que passamos
        // A condição deve ser uma arrow function
        
        //.forEach(condicao) é um for que aplica uma arrow function para cada item do array
        Arrays.stream(numeros)
                .filter(num -> num % 2 == 0)
                .forEach(num -> System.out.println(num));
    }

}
